
version: '3.4'

services:
  mysql:
    image: mysql:5.7
    container_name: dbTodo
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3906:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend
  api:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: apiTodo
    volumes:
      - api-data:/app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - mysql
    networks:
      - backend

volumes:
  mysql-data:
  api-data:

networks:
  backend:
