
version: '3.4'

services:
  mysql:
    image: mysql:5.7
    container_name: dbTodo
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoapp
      MYSQL_USER: todoapp
      MYSQL_PASSWORD: p123
    ports:
      - "3506:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:alpine
    container_name: redisTodo
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

  api:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: apiTodo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - backend

volumes:
  mysql-data:
  redis-data:

networks:
  backend:
